In [1]:
# Dependencies
from splinter import Browser
import pandas as pd
from itertools import cycle
import numpy as np

In [2]:
# Pulling data from this url
url = 'https://www.espn.com/nfl/fpi/_/view/efficiencies/season/2015'

In [3]:
# Reading the HTML tables into a list of tables 
tables = pd.read_html(url, header=0)

In [4]:
df = tables[0]

In [8]:
df.index = np.arange(1, len(df)+1)
df

                    Team
1      Carolina Panthers
2     Kansas City Chiefs
3      Arizona Cardinals
4   New England Patriots
5     Cincinnati Bengals
6       Seattle Seahawks
7         Denver Broncos
8      Minnesota Vikings
9    Pittsburgh Steelers
10         New York Jets
11     Green Bay Packers
12   Washington Redskins
13       New York Giants
14        Houston Texans
15         Buffalo Bills
16       Atlanta Falcons
17        St. Louis Rams
18         Detroit Lions
19    New Orleans Saints
20       Oakland Raiders
21   Philadelphia Eagles
22    Indianapolis Colts
23         Chicago Bears
24  Tampa Bay Buccaneers
25    San Diego Chargers
26      Baltimore Ravens
27        Dallas Cowboys
28        Miami Dolphins
29  Jacksonville Jaguars
30      Tennessee Titans
31   San Francisco 49ers
32      Cleveland Browns

In [5]:
df1 = tables[1]

In [6]:
df1 = df1.rename(columns=df1.iloc[0]).drop(df1.index[0])

In [7]:
df1

     W-L-T   EFF RNK   EFF RNK   EFF RNK   EFF RNK
1   17-2-0  74.5   1  66.6   3  73.5   2  47.1  23
2   12-6-0  68.0   2  55.3  10  69.2   3  58.1   2
3   14-4-0  67.5   3  72.5   1  60.5   9  34.3  32
4   13-5-0  67.4   4  63.5   4  60.6   8  57.7   4
5   12-5-0  66.7   5  62.8   5  62.0   6  53.3  14
6   11-7-0  63.4   6  60.8   6  58.6  12  53.4  13
7   15-4-0  60.3   7  35.3  29  75.3   1  58.0   3
8   11-6-0  60.0   8  52.9  13  61.2   7  53.4  11
9   11-7-0  59.1   9  56.9   8  60.0  11  43.3  28
10  10-6-0  57.5  10  52.5  14  65.5   4  35.6  30
11  11-7-0  57.1  11  55.4   9  54.7  13  50.3  17
12   9-8-0  50.7  12  54.9  11  46.6  17  48.1  20
13  6-10-0  49.9  13  59.0   7  38.4  29  57.2   6
14   9-8-0  49.7  14  41.3  22  62.4   5  41.1  29
15   8-8-0  49.5  15  51.8  15  48.2  16  49.0  19
16   8-8-0  49.2  16  53.0  12  46.1  18  46.2  25
17   7-9-0  46.2  17  31.2  32  60.3  10  53.4  12
18   7-9-0  45.3  18  50.4  17  39.8  26  55.6   8
19   7-9-0  45.0  19  68.2   2  22.1  32  53.6  10
20   7-9-0  44.9  20  44.8  19  48.4  15  47.7  21
21   7-9-0  44.7  21  42.0  21  45.2  20  61.8   1
22   8-8-0  43.3  22  38.2  23  51.5  14  50.0  18
23  6-10-0  40.9  23  47.7  18  39.7  27  44.7  26
24  6-10-0  40.6  24  51.6  16  40.7  25  35.3  31
25  4-12-0  38.8  25  43.9  20  38.6  28  47.5  22
26  5-11-0  38.7  26  35.9  28  43.0  21  57.7   5
27  4-12-0  37.5  27  36.6  27  45.5  19  46.5  24
28  6-10-0  37.4  28  36.9  25  41.4  22  56.5   7
29  5-11-0  36.8  29  37.2  24  40.9  24  53.8   9
30  3-13-0  32.9  30  31.7  31  41.4  23  50.7  16
31  5-11-0  31.3  31  33.8  30  37.1  30  50.9  15
32  3-13-0  31.2  32  36.7  26  35.6  31  44.3  27

In [11]:
eff_15 = df.join(df1, how='outer')
eff_15

                    Team   W-L-T   EFF RNK   EFF RNK   EFF RNK   EFF RNK
1      Carolina Panthers  17-2-0  74.5   1  66.6   3  73.5   2  47.1  23
2     Kansas City Chiefs  12-6-0  68.0   2  55.3  10  69.2   3  58.1   2
3      Arizona Cardinals  14-4-0  67.5   3  72.5   1  60.5   9  34.3  32
4   New England Patriots  13-5-0  67.4   4  63.5   4  60.6   8  57.7   4
5     Cincinnati Bengals  12-5-0  66.7   5  62.8   5  62.0   6  53.3  14
6       Seattle Seahawks  11-7-0  63.4   6  60.8   6  58.6  12  53.4  13
7         Denver Broncos  15-4-0  60.3   7  35.3  29  75.3   1  58.0   3
8      Minnesota Vikings  11-6-0  60.0   8  52.9  13  61.2   7  53.4  11
9    Pittsburgh Steelers  11-7-0  59.1   9  56.9   8  60.0  11  43.3  28
10         New York Jets  10-6-0  57.5  10  52.5  14  65.5   4  35.6  30
11     Green Bay Packers  11-7-0  57.1  11  55.4   9  54.7  13  50.3  17
12   Washington Redskins   9-8-0  50.7  12  54.9  11  46.6  17  48.1  20
13       New York Giants  6-10-0  49.9  13  59.0   7  38.4  29  57.2   6
14        Houston Texans   9-8-0  49.7  14  41.3  22  62.4   5  41.1  29
15         Buffalo Bills   8-8-0  49.5  15  51.8  15  48.2  16  49.0  19
16       Atlanta Falcons   8-8-0  49.2  16  53.0  12  46.1  18  46.2  25
17        St. Louis Rams   7-9-0  46.2  17  31.2  32  60.3  10  53.4  12
18         Detroit Lions   7-9-0  45.3  18  50.4  17  39.8  26  55.6   8
19    New Orleans Saints   7-9-0  45.0  19  68.2   2  22.1  32  53.6  10
20       Oakland Raiders   7-9-0  44.9  20  44.8  19  48.4  15  47.7  21
21   Philadelphia Eagles   7-9-0  44.7  21  42.0  21  45.2  20  61.8   1
22    Indianapolis Colts   8-8-0  43.3  22  38.2  23  51.5  14  50.0  18
23         Chicago Bears  6-10-0  40.9  23  47.7  18  39.7  27  44.7  26
24  Tampa Bay Buccaneers  6-10-0  40.6  24  51.6  16  40.7  25  35.3  31
25    San Diego Chargers  4-12-0  38.8  25  43.9  20  38.6  28  47.5  22
26      Baltimore Ravens  5-11-0  38.7  26  35.9  28  43.0  21  57.7   5
27        Dallas Cowboys  4-12-0  37.5  27  36.6  27  45.5  19  46.5  24
28        Miami Dolphins  6-10-0  37.4  28  36.9  25  41.4  22  56.5   7
29  Jacksonville Jaguars  5-11-0  36.8  29  37.2  24  40.9  24  53.8   9
30      Tennessee Titans  3-13-0  32.9  30  31.7  31  41.4  23  50.7  16
31   San Francisco 49ers  5-11-0  31.3  31  33.8  30  37.1  30  50.9  15
32      Cleveland Browns  3-13-0  31.2  32  36.7  26  35.6  31  44.3  27

In [12]:
eff = cycle(['2015'])
eff_15['Year'] = [next(eff) for n in range(len(eff_15))]

In [13]:
eff_15

                    Team   W-L-T   EFF RNK   EFF RNK   EFF RNK   EFF RNK  Year
1      Carolina Panthers  17-2-0  74.5   1  66.6   3  73.5   2  47.1  23  2015
2     Kansas City Chiefs  12-6-0  68.0   2  55.3  10  69.2   3  58.1   2  2015
3      Arizona Cardinals  14-4-0  67.5   3  72.5   1  60.5   9  34.3  32  2015
4   New England Patriots  13-5-0  67.4   4  63.5   4  60.6   8  57.7   4  2015
5     Cincinnati Bengals  12-5-0  66.7   5  62.8   5  62.0   6  53.3  14  2015
6       Seattle Seahawks  11-7-0  63.4   6  60.8   6  58.6  12  53.4  13  2015
7         Denver Broncos  15-4-0  60.3   7  35.3  29  75.3   1  58.0   3  2015
8      Minnesota Vikings  11-6-0  60.0   8  52.9  13  61.2   7  53.4  11  2015
9    Pittsburgh Steelers  11-7-0  59.1   9  56.9   8  60.0  11  43.3  28  2015
10         New York Jets  10-6-0  57.5  10  52.5  14  65.5   4  35.6  30  2015
11     Green Bay Packers  11-7-0  57.1  11  55.4   9  54.7  13  50.3  17  2015
12   Washington Redskins   9-8-0  50.7  12  54.9  11  46.6  17  48.1  20  2015
13       New York Giants  6-10-0  49.9  13  59.0   7  38.4  29  57.2   6  2015
14        Houston Texans   9-8-0  49.7  14  41.3  22  62.4   5  41.1  29  2015
15         Buffalo Bills   8-8-0  49.5  15  51.8  15  48.2  16  49.0  19  2015
16       Atlanta Falcons   8-8-0  49.2  16  53.0  12  46.1  18  46.2  25  2015
17        St. Louis Rams   7-9-0  46.2  17  31.2  32  60.3  10  53.4  12  2015
18         Detroit Lions   7-9-0  45.3  18  50.4  17  39.8  26  55.6   8  2015
19    New Orleans Saints   7-9-0  45.0  19  68.2   2  22.1  32  53.6  10  2015
20       Oakland Raiders   7-9-0  44.9  20  44.8  19  48.4  15  47.7  21  2015
21   Philadelphia Eagles   7-9-0  44.7  21  42.0  21  45.2  20  61.8   1  2015
22    Indianapolis Colts   8-8-0  43.3  22  38.2  23  51.5  14  50.0  18  2015
23         Chicago Bears  6-10-0  40.9  23  47.7  18  39.7  27  44.7  26  2015
24  Tampa Bay Buccaneers  6-10-0  40.6  24  51.6  16  40.7  25  35.3  31  2015
25    San Diego Chargers  4-12-0  38.8  25  43.9  20  38.6  28  47.5  22  2015
26      Baltimore Ravens  5-11-0  38.7  26  35.9  28  43.0  21  57.7   5  2015
27        Dallas Cowboys  4-12-0  37.5  27  36.6  27  45.5  19  46.5  24  2015
28        Miami Dolphins  6-10-0  37.4  28  36.9  25  41.4  22  56.5   7  2015
29  Jacksonville Jaguars  5-11-0  36.8  29  37.2  24  40.9  24  53.8   9  2015
30      Tennessee Titans  3-13-0  32.9  30  31.7  31  41.4  23  50.7  16  2015
31   San Francisco 49ers  5-11-0  31.3  31  33.8  30  37.1  30  50.9  15  2015
32      Cleveland Browns  3-13-0  31.2  32  36.7  26  35.6  31  44.3  27  2015

In [14]:
eff_15.to_csv('results/eff_15.csv',index=False)