In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("538.csv", header=0)

In [3]:
df.head()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,TEAM,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year
0,1658,NaN,NaN,Chiefs,AFC West,11-5,NaN,+113.6,86%,69%,25%,14%,1,2020
1,1647,NaN,NaN,Ravens,AFC North,11-5,NaN,+106.7,82%,55%,24%,12%,1,2020
2,1614,NaN,NaN,Saints,NFC South,10-6,NaN,+75.0,72%,51%,17%,9%,1,2020
3,1601,NaN,NaN,49ers,NFC West,10-6,NaN,+66.8,68%,41%,15%,7%,1,2020
4,1573,NaN,NaN,Steelers,AFC North,10-6,NaN,+57.0,65%,30%,10%,5%,1,2020

In [4]:
df = df.sort_values(["Year", "Before Week"])

In [5]:
def cleanWins(record):
    if("." in str(record)):
        return record
    elif (type(record) != float) and ("-" in record):
        regx = re.compile("\d+-")
        wins = regx.search(record)
        if wins != None:
            wins = wins[0][:-1]
        #losses = regx.search(record)[1]
            return wins

In [6]:
def cleanLs(record):
    if("." in str(record)):
        record = float(record)
        record = 16 - record
        return record
    elif (type(record) != float) and ("-" in record):
        regx = re.compile("-\d+")
        wins = regx.search(record)
        if wins != None:
            wins = wins[0][1:]
        #losses = regx.search(record)[1]
            return wins

In [7]:
df = df.assign(PROJ_WINS2 = lambda x: x["PROJ WINS"].apply(cleanWins))

In [8]:
df = df.assign(PROJ_LOSSES2 = lambda x: x["PROJ WINS"].apply(cleanLs))

In [9]:
df.shape

(3620, 16)

In [10]:
def realWins(name):
    regex = re.compile(".\d+-\d+")
    record = regex.search(name)
    if record != None:
        record = record[0]
        record = record[1:]
        rec = record.split("-")
        wins = rec[0]
        losses = rec[1]
        return wins
    else:
        return 0

In [11]:
df = df.assign(REAL_WINS = lambda x: x.TEAM.apply(realWins))

In [12]:
def realLss(name):
    regex = re.compile(".\d+-\d+")
    record = regex.search(name)
    if record != None:
        record = record[0]
        record = record[1:]
        rec = record.split("-")
        wins = rec[0]
        losses = rec[1]
        return losses
    else:
        return 0

In [13]:
df = df.assign(REAL_LOSSES = lambda x: x.TEAM.apply(realLss))

In [14]:
def cleanName(name):
    regex = re.compile("\d+-\d+")
    record = regex.search(name)
    if record != None:
        record = record[0]
        name = name.replace(record, "")
        return name
    else:
        return name

In [15]:
df = df.assign(CLEAN_NAME = lambda x: x.TEAM.apply(cleanName))

In [16]:
df = df.reset_index(drop=True)

In [162]:
df.to_csv("cleanerELO.csv")

In [ ]:
df.assign(PROJ_WINS2 = lambda x: x["PROJ WINS"].apply(cleanWins))

In [17]:
type(12.3)

float

In [18]:
regx = re.compile("\d+-\d+")

In [19]:
regx.search("s2-2")

In [20]:
sg = "12-3"

In [21]:
sg.split("-")

['12', '3']

### Final ELO

In [242]:
df_a = pd.read_csv("cleanerELO.csv", header=0, index_col=0)

In [243]:
df_a.head()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,TEAM,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year,PROJ_WINS2,PROJ_LOSSES2,REAL_WINS,REAL_LOSSES,CLEAN_NAME
0,1678,NaN,NaN,Seattle,NFC West,11.1,4.9,+109.6,78%,60%,42%,15%,1,2015,11.1,4.9,0,0,Seattle
1,1664,NaN,NaN,New England,AFC East,11.3,4.7,+118.5,80%,62%,44%,14%,1,2015,11.3,4.7,0,0,New England
2,1601,NaN,NaN,Green Bay,NFC North,9.7,6.2,+61.3,62%,49%,25%,7%,1,2015,9.7,6.3,0,0,Green Bay
3,1595,NaN,NaN,Denver,AFC West,9.6,6.4,+55.9,59%,44%,23%,6%,1,2015,9.6,6.4,0,0,Denver
4,1590,NaN,NaN,Dallas,NFC East,9.8,6.2,+62.6,63%,47%,26%,6%,1,2015,9.8,6.2,0,0,Dallas

In [22]:
df_a = df

In [23]:
df_ab = df_a.loc[:, ["CLEAN_NAME", "ELO WITH QB", "ELO CHANGE", "CURRENT QB ADJ", "DIVISION", "PROJ_WINS2", "PROJ_LOSSES2", "REAL_WINS", "REAL_LOSSES", "POINT DIFF", "MAKE PLAYOFFS","WIN DIVISION", "1st-Round Bye", "Win Superbowl", "Before Week", "Year"]]

In [24]:
df_ab.head()

,CLEAN_NAME,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ_WINS2,PROJ_LOSSES2,REAL_WINS,REAL_LOSSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year
0,Seattle,1678,NaN,NaN,NFC West,11.1,4.9,0,0,+109.6,78%,60%,42%,15%,1,2015
1,New England,1664,NaN,NaN,AFC East,11.3,4.7,0,0,+118.5,80%,62%,44%,14%,1,2015
2,Green Bay,1601,NaN,NaN,NFC North,9.7,6.3,0,0,+61.3,62%,49%,25%,7%,1,2015
3,Denver,1595,NaN,NaN,AFC West,9.6,6.4,0,0,+55.9,59%,44%,23%,6%,1,2015
4,Dallas,1590,NaN,NaN,NFC East,9.8,6.2,0,0,+62.6,63%,47%,26%,6%,1,2015

In [25]:
df_ab.tail()

,CLEAN_NAME,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ_WINS2,PROJ_LOSSES2,REAL_WINS,REAL_LOSSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year
3615,Lions,1406,-24.0,NaN,NFC North,6,10,3,5,-78.4,5%,<1%,<1%,<1%,10,2020
3616,Giants,1367,14.0,NaN,NFC East,4,12,2,7,-94.1,7%,7%,<1%,<1%,10,2020
3617,Cowboys,1329,-3.0,-13.0,NFC East,4,12,2,7,-134.1,6%,6%,<1%,<1%,10,2020
3618,Jaguars,1298,-8.0,-91.0,AFC South,2,14,1,7,-180.8,<1%,<1%,<1%,<1%,10,2020
3619,Jets,1295,-17.0,1.0,AFC East,2,14,0,9,-217.7,<1%,—,—,<1%,10,2020

In [26]:
df_ab

,CLEAN_NAME,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ_WINS2,PROJ_LOSSES2,REAL_WINS,REAL_LOSSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year
0,Seattle,1678,NaN,NaN,NFC West,11.1,4.9,0,0,+109.6,78%,60%,42%,15%,1,2015
1,New England,1664,NaN,NaN,AFC East,11.3,4.7,0,0,+118.5,80%,62%,44%,14%,1,2015
2,Green Bay,1601,NaN,NaN,NFC North,9.7,6.3,0,0,+61.3,62%,49%,25%,7%,1,2015
3,Denver,1595,NaN,NaN,AFC West,9.6,6.4,0,0,+55.9,59%,44%,23%,6%,1,2015
4,Dallas,1590,NaN,NaN,NFC East,9.8,6.2,0,0,+62.6,63%,47%,26%,6%,1,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3615,Lions,1406,-24.0,NaN,NFC North,6,10,3,5,-78.4,5%,<1%,<1%,<1%,10,2020
3616,Giants,1367,14.0,NaN,NFC East,4,12,2,7,-94.1,7%,7%,<1%,<1%,10,2020
3617,Cowboys,1329,-3.0,-13.0,NFC East,4,12,2,7,-134.1,6%,6%,<1%,<1%,10,2020
3618,Jaguars,1298,-8.0,-91.0,AFC South,2,14,1,7,-180.8,<1%,<1%,<1%,<1%,10,2020
3619,Jets,1295,-17.0,1.0,AFC East,2,14,0,9,-217.7,<1%,—,—,<1%,10,2020

In [27]:
Teams = ["Arizona Cardinals",
"Atlanta Falcons",
"Baltimore Ravens",
"Buffalo Bills",
"Carolina Panthers",
"Chicago Bears",
"Cincinnati Bengals",
"Cleveland Browns",
"Dallas Cowboys",
"Denver Broncos",
"Detroit Lions",
"Green Bay Packers",
"Houston Texans",
"Indianapolis Colts",
"Jacksonville Jaguars",
"Kansas City Chiefs",
"San Diego Chargers",
"St. Louis Rams",
"Oakland Raiders",
"Miami Dolphins",
"Minnesota Vikings",
"New York Giants",
"New York Jets",
"New England Patriots",
"New Orleans Saints",
"Philadelphia Eagles",
"Pittsburgh Steelers",
"San Francisco 49ers",
"Seattle Seahawks",
"Tampa Bay Buccaneers",
"Tennessee Titans",
"Washington Redskins"]

In [28]:
def getNames(teamCol):
    dict_0 = {}
    for team in teamCol:
        if team in dict_0.keys():
            dict_0[team] += 1
        else:
            dict_0[team] = 1
    return dict_0

In [29]:
df_ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CLEAN_NAME      3620 non-null   object
 1   ELO WITH QB     3620 non-null   int64
 2   ELO CHANGE      2799 non-null   float64
 3   CURRENT QB ADJ  112 non-null    float64
 4   DIVISION        3620 non-null   object
 5   PROJ_WINS2      2866 non-null   object
 6   PROJ_LOSSES2    2866 non-null   object
 7   REAL_WINS       3620 non-null   object
 8   REAL_LOSSES     3620 non-null   object
 9   POINT DIFF      3232 non-null   object
 10  MAKE PLAYOFFS   3620 non-null   object
 11  WIN DIVISION    3620 non-null   object
 12  1st-Round Bye   3620 non-null   object
 13  Win Superbowl   3588 non-null   object
 14  Before Week     3620 non-null   int64
 15  Year            3620 non-null   int64
dtypes: float64(2), int64(3), object(11)
memory usage: 452.6+ KB

In [30]:
d = getNames(df_ab.CLEAN_NAME)

In [31]:
d

{'Seattle': 91,
 'New England': 105,
 'Green Bay': 86,
 'Denver': 102,
 'Dallas': 105,
 'Indianapolis': 105,
 'Baltimore': 105,
 'Pittsburgh': 85,
 'Philadelphia': 105,
 'Arizona': 68,
 'Cincinnati': 89,
 'Kansas City': 105,
 'Detroit': 82,
 'Carolina': 102,
 'Buffalo': 102,
 'San Francisco': 102,
 'San Diego': 42,
 'Houston': 105,
 'New Orleans': 105,
 'Miami': 102,
 'N.Y. Giants': 102,
 'Minnesota': 86,
 'St. Louis': 21,
 'Atlanta': 102,
 'N.Y. Jets': 102,
 'Cleveland': 85,
 'Chicago': 105,
 'Oakland': 102,
 'Tampa Bay': 102,
 'Washington': 99,
 'Jacksonville': 102,
 'Tennessee': 102,
 'Los Angeles': 21,
 'Seattle-1': 14,
 'Arizona-1': 34,
 'Washington-1': 13,
 'Cincinnati-1': 13,
 'L.A. Chargers': 63,
 'L.A. Rams': 63,
 'Pittsburgh-1': 17,
 'Cleveland-1': 17,
 'Minnesota-1': 16,
 'Green Bay-1': 16,
 'Detroit-1': 20,
 'Chiefs': 10,
 'Ravens': 10,
 'Saints': 10,
 '49ers': 10,
 'Steelers': 10,
 'Cowboys': 10,
 'Packers': 10,
 'Patriots': 10,
 'Titans': 10,
 'Eagles': 3,
 'Seahawks': 10,
 'Vikings': 10,
 'Rams': 10,
 'Buccaneers': 10,
 'Bills': 10,
 'Bears': 10,
 'Colts': 10,
 'Texans': 10,
 'Falcons': 10,
 'Browns': 10,
 'Broncos': 10,
 'Raiders': 10,
 'Cardinals': 10,
 'Chargers': 10,
 'Jets': 10,
 'Lions': 10,
 'Dolphins': 10,
 'Panthers': 10,
 'Giants': 10,
 'Bengals': 3,
 'Jaguars': 10,
 'Eagles-1': 7,
 'Bengals-1': 7}

In [32]:
pat = re.compile("(\d+-\d+)(-\d+)?")

In [33]:
pat.search("1-2-1")

In [34]:
def cleanName(name):
    regex = re.compile("(\d+-\d+)(-\d+)?")
    record = regex.search(name)
    if record != None:
        record = record[0]
        name = name.replace(record, "")
        return name
    else:
        return name

In [35]:
df_a = df_a.assign(CLEAN_NAME2 = lambda x : x.TEAM.apply(cleanName))

In [36]:
def realWins(name):
    regex = re.compile("(\d+-\d+)(-\d+)?")
    record = regex.search(name)
    if record != None:
        record = record[0]
        #record = record[1:]
        rec = record.split("-")
        wins = rec[0]
        losses = rec[1]
        return wins
    else:
        return 0

In [37]:
def realLss(name):
    regex = re.compile("(\d+-\d+)(-\d+)?")
    record = regex.search(name)
    if record != None:
        record = record[0]
        #record = record[1:]
        rec = record.split("-")
        wins = rec[0]
        losses = rec[1]
        return losses
    else:
        return 0

In [38]:
def realTies(name):
    regex = re.compile("(\d+-\d+)(-\d+)?")
    record = regex.search(name)
    if record != None:
        record = record[0]
        #record = record[1:]
        rec = record.split("-")
        wins = rec[0]
        losses = rec[1]
        if len(rec) > 2:
            ties = rec[2]
            return ties
        else:
            return 0
    else:
        return 0

In [39]:
df_a.columns

Index(['ELO WITH QB', 'ELO CHANGE', 'CURRENT QB ADJ', 'TEAM', 'DIVISION',
       'PROJ WINS', 'PROJ LOSES', 'POINT DIFF', 'MAKE PLAYOFFS',
       'WIN DIVISION', '1st-Round Bye', 'Win Superbowl', 'Before Week', 'Year',
       'PROJ_WINS2', 'PROJ_LOSSES2', 'REAL_WINS', 'REAL_LOSSES', 'CLEAN_NAME',
       'CLEAN_NAME2'],
      dtype='object')

In [40]:
df_a = df_a.assign(REAL_WINS2 = lambda x: x.TEAM.apply(realWins))

In [41]:
df_a = df_a.assign(REAL_LOSSES2 = lambda x: x.TEAM.apply(realLss))

In [42]:
df_a = df_a.assign(REAL_TIES = lambda x: x.TEAM.apply(realTies))

In [43]:
df_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELO WITH QB     3620 non-null   int64
 1   ELO CHANGE      2799 non-null   float64
 2   CURRENT QB ADJ  112 non-null    float64
 3   TEAM            3620 non-null   object
 4   DIVISION        3620 non-null   object
 5   PROJ WINS       3264 non-null   object
 6   PROJ LOSES      2368 non-null   object
 7   POINT DIFF      3232 non-null   object
 8   MAKE PLAYOFFS   3620 non-null   object
 9   WIN DIVISION    3620 non-null   object
 10  1st-Round Bye   3620 non-null   object
 11  Win Superbowl   3588 non-null   object
 12  Before Week     3620 non-null   int64
 13  Year            3620 non-null   int64
 14  PROJ_WINS2      2866 non-null   object
 15  PROJ_LOSSES2    2866 non-null   object
 16  REAL_WINS       3620 non-null   object
 17  REAL_LOSSES     3620 non-null   object
 18  CLEAN_NAME      3620 non-null   object
 19  CLEAN_NAME2     3620 non-null   object
 20  REAL_WINS2      3620 non-null   object
 21  REAL_LOSSES2    3620 non-null   object
 22  REAL_TIES       3620 non-null   object
dtypes: float64(2), int64(3), object(18)
memory usage: 650.6+ KB

In [44]:
def cleanWins(record):
    if("." in str(record)):
        return record
    elif (type(record) != float) and ("-" not in record):
        return record
    elif (type(record) != float) and ("-" in record):
        regx = re.compile("\d+-")
        wins = regx.search(record)
        if wins != None:
            wins = wins[0][:-1]
        #losses = regx.search(record)[1]
            return wins

In [45]:
def cleanLs(record):
    if("." in str(record)):
        record = float(record)
        record = 16 - record
        return record
    elif (type(record) != float) and ("-" not in record):
        return record
    elif (type(record) != float) and ("-" in record):
        regx = re.compile("-\d+")
        wins = regx.search(record)
        if wins != None:
            wins = wins[0][1:]
        #losses = regx.search(record)[1]
            return wins

In [46]:
df_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELO WITH QB     3620 non-null   int64
 1   ELO CHANGE      2799 non-null   float64
 2   CURRENT QB ADJ  112 non-null    float64
 3   TEAM            3620 non-null   object
 4   DIVISION        3620 non-null   object
 5   PROJ WINS       3264 non-null   object
 6   PROJ LOSES      2368 non-null   object
 7   POINT DIFF      3232 non-null   object
 8   MAKE PLAYOFFS   3620 non-null   object
 9   WIN DIVISION    3620 non-null   object
 10  1st-Round Bye   3620 non-null   object
 11  Win Superbowl   3588 non-null   object
 12  Before Week     3620 non-null   int64
 13  Year            3620 non-null   int64
 14  PROJ_WINS2      2866 non-null   object
 15  PROJ_LOSSES2    2866 non-null   object
 16  REAL_WINS       3620 non-null   object
 17  REAL_LOSSES     3620 non-null   object
 18  CLEAN_NAME      3620 non-null   object
 19  CLEAN_NAME2     3620 non-null   object
 20  REAL_WINS2      3620 non-null   object
 21  REAL_LOSSES2    3620 non-null   object
 22  REAL_TIES       3620 non-null   object
dtypes: float64(2), int64(3), object(18)
memory usage: 650.6+ KB

In [47]:
df_a =df_a.assign(PROJ_WINS3 = lambda x: x["PROJ WINS"].apply(cleanWins))

In [48]:
df_a = df_a.assign(PROJ_LOSS3 = lambda x: x["PROJ WINS"].apply(cleanLs))

In [327]:
df_a.to_csv("cleanestELO.csv", index=False)

# Step 3

In [330]:
df_h = pd.read_csv("cleanestELO.csv", header=0)

In [50]:
df_h = df_a

In [52]:
df_h.head()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,TEAM,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,...,PROJ_LOSSES2,REAL_WINS,REAL_LOSSES,CLEAN_NAME,CLEAN_NAME2,REAL_WINS2,REAL_LOSSES2,REAL_TIES,PROJ_WINS3,PROJ_LOSS3
0,1678,NaN,NaN,Seattle,NFC West,11.1,4.9,+109.6,78%,60%,...,4.9,0,0,Seattle,Seattle,0,0,0,11.1,4.9
1,1664,NaN,NaN,New England,AFC East,11.3,4.7,+118.5,80%,62%,...,4.7,0,0,New England,New England,0,0,0,11.3,4.7
2,1601,NaN,NaN,Green Bay,NFC North,9.7,6.2,+61.3,62%,49%,...,6.3,0,0,Green Bay,Green Bay,0,0,0,9.7,6.3
3,1595,NaN,NaN,Denver,AFC West,9.6,6.4,+55.9,59%,44%,...,6.4,0,0,Denver,Denver,0,0,0,9.6,6.4
4,1590,NaN,NaN,Dallas,NFC East,9.8,6.2,+62.6,63%,47%,...,6.2,0,0,Dallas,Dallas,0,0,0,9.8,6.2

In [53]:
right_cols = list(df_h.columns[-6:])

In [54]:
left_cols = list(df_h.columns[:14])

In [55]:
for x in right_cols:
    left_cols.append(x)

In [56]:
left_cols

['ELO WITH QB',
 'ELO CHANGE',
 'CURRENT QB ADJ',
 'TEAM',
 'DIVISION',
 'PROJ WINS',
 'PROJ LOSES',
 'POINT DIFF',
 'MAKE PLAYOFFS',
 'WIN DIVISION',
 '1st-Round Bye',
 'Win Superbowl',
 'Before Week',
 'Year',
 'CLEAN_NAME2',
 'REAL_WINS2',
 'REAL_LOSSES2',
 'REAL_TIES',
 'PROJ_WINS3',
 'PROJ_LOSS3']

In [57]:
left_cols.remove("TEAM")

In [58]:
left_cols

['ELO WITH QB',
 'ELO CHANGE',
 'CURRENT QB ADJ',
 'DIVISION',
 'PROJ WINS',
 'PROJ LOSES',
 'POINT DIFF',
 'MAKE PLAYOFFS',
 'WIN DIVISION',
 '1st-Round Bye',
 'Win Superbowl',
 'Before Week',
 'Year',
 'CLEAN_NAME2',
 'REAL_WINS2',
 'REAL_LOSSES2',
 'REAL_TIES',
 'PROJ_WINS3',
 'PROJ_LOSS3']

In [59]:
df_h2 = df_h.loc[:, left_cols]

In [60]:
df_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELO WITH QB     3620 non-null   int64
 1   ELO CHANGE      2799 non-null   float64
 2   CURRENT QB ADJ  112 non-null    float64
 3   TEAM            3620 non-null   object
 4   DIVISION        3620 non-null   object
 5   PROJ WINS       3264 non-null   object
 6   PROJ LOSES      2368 non-null   object
 7   POINT DIFF      3232 non-null   object
 8   MAKE PLAYOFFS   3620 non-null   object
 9   WIN DIVISION    3620 non-null   object
 10  1st-Round Bye   3620 non-null   object
 11  Win Superbowl   3588 non-null   object
 12  Before Week     3620 non-null   int64
 13  Year            3620 non-null   int64
 14  PROJ_WINS2      2866 non-null   object
 15  PROJ_LOSSES2    2866 non-null   object
 16  REAL_WINS       3620 non-null   object
 17  REAL_LOSSES     3620 non-null   object
 18  CLEAN_NAME      3620 non-null   object
 19  CLEAN_NAME2     3620 non-null   object
 20  REAL_WINS2      3620 non-null   object
 21  REAL_LOSSES2    3620 non-null   object
 22  REAL_TIES       3620 non-null   object
 23  PROJ_WINS3      3264 non-null   object
 24  PROJ_LOSS3      3264 non-null   object
dtypes: float64(2), int64(3), object(20)
memory usage: 707.2+ KB

In [61]:
df_h2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ELO WITH QB     3620 non-null   int64
 1   ELO CHANGE      2799 non-null   float64
 2   CURRENT QB ADJ  112 non-null    float64
 3   DIVISION        3620 non-null   object
 4   PROJ WINS       3264 non-null   object
 5   PROJ LOSES      2368 non-null   object
 6   POINT DIFF      3232 non-null   object
 7   MAKE PLAYOFFS   3620 non-null   object
 8   WIN DIVISION    3620 non-null   object
 9   1st-Round Bye   3620 non-null   object
 10  Win Superbowl   3588 non-null   object
 11  Before Week     3620 non-null   int64
 12  Year            3620 non-null   int64
 13  CLEAN_NAME2     3620 non-null   object
 14  REAL_WINS2      3620 non-null   object
 15  REAL_LOSSES2    3620 non-null   object
 16  REAL_TIES       3620 non-null   object
 17  PROJ_WINS3      3264 non-null   object
 18  PROJ_LOSS3      3264 non-null   object
dtypes: float64(2), int64(3), object(14)
memory usage: 537.5+ KB

In [62]:
df_h2Dict = getNames(df_h2.CLEAN_NAME2)

In [63]:
df_h2Dict

{'Seattle': 105,
 'New England': 105,
 'Green Bay': 102,
 'Denver': 102,
 'Dallas': 105,
 'Indianapolis': 105,
 'Baltimore': 105,
 'Pittsburgh': 102,
 'Philadelphia': 105,
 'Arizona': 102,
 'Cincinnati': 102,
 'Kansas City': 105,
 'Detroit': 102,
 'Carolina': 102,
 'Buffalo': 102,
 'San Francisco': 102,
 'San Diego': 42,
 'Houston': 105,
 'New Orleans': 105,
 'Miami': 102,
 'N.Y. Giants': 102,
 'Minnesota': 102,
 'St. Louis': 21,
 'Atlanta': 102,
 'N.Y. Jets': 102,
 'Cleveland': 102,
 'Chicago': 105,
 'Oakland': 102,
 'Tampa Bay': 102,
 'Washington': 112,
 'Jacksonville': 102,
 'Tennessee': 102,
 'Los Angeles': 21,
 'L.A. Chargers': 63,
 'L.A. Rams': 63,
 'Chiefs': 10,
 'Ravens': 10,
 'Saints': 10,
 '49ers': 10,
 'Steelers': 10,
 'Cowboys': 10,
 'Packers': 10,
 'Patriots': 10,
 'Titans': 10,
 'Eagles': 10,
 'Seahawks': 10,
 'Vikings': 10,
 'Rams': 10,
 'Buccaneers': 10,
 'Bills': 10,
 'Bears': 10,
 'Colts': 10,
 'Texans': 10,
 'Falcons': 10,
 'Browns': 10,
 'Broncos': 10,
 'Raiders': 10,
 'Cardinals': 10,
 'Chargers': 10,
 'Jets': 10,
 'Lions': 10,
 'Dolphins': 10,
 'Panthers': 10,
 'Giants': 10,
 'Bengals': 10,
 'Jaguars': 10}

In [374]:
with open("dict.txt", "w") as file:
    file.write(str(df_h2Dict))

In [64]:
Teams

['Arizona Cardinals',
 'Atlanta Falcons',
 'Baltimore Ravens',
 'Buffalo Bills',
 'Carolina Panthers',
 'Chicago Bears',
 'Cincinnati Bengals',
 'Cleveland Browns',
 'Dallas Cowboys',
 'Denver Broncos',
 'Detroit Lions',
 'Green Bay Packers',
 'Houston Texans',
 'Indianapolis Colts',
 'Jacksonville Jaguars',
 'Kansas City Chiefs',
 'San Diego Chargers',
 'St. Louis Rams',
 'Oakland Raiders',
 'Miami Dolphins',
 'Minnesota Vikings',
 'New York Giants',
 'New York Jets',
 'New England Patriots',
 'New Orleans Saints',
 'Philadelphia Eagles',
 'Pittsburgh Steelers',
 'San Francisco 49ers',
 'Seattle Seahawks',
 'Tampa Bay Buccaneers',
 'Tennessee Titans',
 'Washington Redskins']

In [65]:
parser = {
    "Seattle": "Seattle Seahawks",
    "Seahawks": "Seattle Seahawks",
    "New England": 'New England Patriots',
    'Patriots': 'New England Patriots',
    "Green Bay": 'Green Bay Packers',
    "Packers": 'Green Bay Packers',
    'Denver': 'Denver Broncos',
    "Broncos": 'Denver Broncos',
    "Dallas": 'Dallas Cowboys',
    "Cowboys": 'Dallas Cowboys',
    'Indianapolis': 'Indianapolis Colts',
    "Colts": 'Indianapolis Colts',
    'Baltimore': 'Baltimore Ravens',
    "Ravens": 'Baltimore Ravens',
    'Pittsburgh': 'Pittsburgh Steelers',
    "Steelers": 'Pittsburgh Steelers',
    'Philadelphia': 'Philadelphia Eagles',
    'Eagles': 'Philadelphia Eagles',
    'Arizona': 'Arizona Cardinals',
    "Cardinals": 'Arizona Cardinals',
    'Cincinnati': 'Cincinnati Bengals',
    'Bengals': 'Cincinnati Bengals',
    'Kansas City': 'Kansas City Chiefs',
    "Chiefs": 'Kansas City Chiefs',
    'Detroit': "Detroit Lions",
    "Lions": "Detroit Lions",
    'Carolina': 'Carolina Panthers',
    "Panthers": 'Carolina Panthers',
    'Buffalo': "Buffalo Bills",
    "Bills": "Buffalo Bills",
    'San Francisco': 'San Francisco 49ers',
    "49ers": 'San Francisco 49ers',
    'Houston': 'Houston Texans',
    "Texans": 'Houston Texans',
    'New Orleans': 'New Orleans Saints',
    "Saints": 'New Orleans Saints',
    'Miami': 'Miami Dolphins',
    "Dolphins": 'Miami Dolphins',
    'N.Y. Giants':'New York Giants',
    "Giants": 'New York Giants', 
    'Minnesota': 'Minnesota Vikings',
    "Vikings": 'Minnesota Vikings', 
    'San Diego': "San Diego Chargers",
    'L.A. Chargers': "San Diego Chargers",
    'Chargers': "San Diego Chargers",
    'St. Louis': "St. Louis Rams",
    'Los Angeles': "St. Louis Rams",
    'L.A. Rams': "St. Louis Rams",
    'Rams': "St. Louis Rams",
    'Atlanta': "Atlanta Falcons",
    'Falcons': "Atlanta Falcons",
    'N.Y. Jets': 'New York Jets',
    'Jets': 'New York Jets', 
    'Cleveland': 'Cleveland Browns',
    'Browns': 'Cleveland Browns',
    'Chicago': 'Chicago Bears',
    'Bears': 'Chicago Bears',
    'Oakland': 'Oakland Raiders',
    'Raiders': 'Oakland Raiders',
    'Tampa Bay': 'Tampa Bay Buccaneers',
    'Buccaneers': 'Tampa Bay Buccaneers',
    'Washington': 'Washington Redskins',
    'Jacksonville': 'Jacksonville Jaguars',
    'Jaguars': 'Jacksonville Jaguars',
    'Tennessee': 'Tennessee Titans',
    'Titans': 'Tennessee Titans',
}

In [66]:
def cleanNamez(name):
    return parser[name]

In [67]:
df_h2.head()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year,CLEAN_NAME2,REAL_WINS2,REAL_LOSSES2,REAL_TIES,PROJ_WINS3,PROJ_LOSS3
0,1678,NaN,NaN,NFC West,11.1,4.9,+109.6,78%,60%,42%,15%,1,2015,Seattle,0,0,0,11.1,4.9
1,1664,NaN,NaN,AFC East,11.3,4.7,+118.5,80%,62%,44%,14%,1,2015,New England,0,0,0,11.3,4.7
2,1601,NaN,NaN,NFC North,9.7,6.2,+61.3,62%,49%,25%,7%,1,2015,Green Bay,0,0,0,9.7,6.3
3,1595,NaN,NaN,AFC West,9.6,6.4,+55.9,59%,44%,23%,6%,1,2015,Denver,0,0,0,9.6,6.4
4,1590,NaN,NaN,NFC East,9.8,6.2,+62.6,63%,47%,26%,6%,1,2015,Dallas,0,0,0,9.8,6.2

In [68]:
df_h2 = df_h2.assign(FinalName = lambda x: x.CLEAN_NAME2.apply(cleanNamez))

In [69]:
df_h3 = df_h2.drop("CLEAN_NAME2", axis=1)

In [70]:
df_h3.columns

Index(['ELO WITH QB', 'ELO CHANGE', 'CURRENT QB ADJ', 'DIVISION', 'PROJ WINS',
       'PROJ LOSES', 'POINT DIFF', 'MAKE PLAYOFFS', 'WIN DIVISION',
       '1st-Round Bye', 'Win Superbowl', 'Before Week', 'Year', 'REAL_WINS2',
       'REAL_LOSSES2', 'REAL_TIES', 'PROJ_WINS3', 'PROJ_LOSS3', 'FinalName'],
      dtype='object')

In [388]:
df_h3.to_csv("cleanestELO.csv", index=False)

In [71]:
df_h3.head()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,Win Superbowl,Before Week,Year,REAL_WINS2,REAL_LOSSES2,REAL_TIES,PROJ_WINS3,PROJ_LOSS3,FinalName
0,1678,NaN,NaN,NFC West,11.1,4.9,+109.6,78%,60%,42%,15%,1,2015,0,0,0,11.1,4.9,Seattle Seahawks
1,1664,NaN,NaN,AFC East,11.3,4.7,+118.5,80%,62%,44%,14%,1,2015,0,0,0,11.3,4.7,New England Patriots
2,1601,NaN,NaN,NFC North,9.7,6.2,+61.3,62%,49%,25%,7%,1,2015,0,0,0,9.7,6.3,Green Bay Packers
3,1595,NaN,NaN,AFC West,9.6,6.4,+55.9,59%,44%,23%,6%,1,2015,0,0,0,9.6,6.4,Denver Broncos
4,1590,NaN,NaN,NFC East,9.8,6.2,+62.6,63%,47%,26%,6%,1,2015,0,0,0,9.8,6.2,Dallas Cowboys

In [73]:
def cleanPercent(s):
    s = str(s)
    s = s.strip()
    if s.startswith(">99"):
        s = "99.99"
    elif s.startswith("<1"):
        s = "1"
    if (">" not in s) and ("%" in s):
        num = s.replace("%", "")
        num = float(num) / 100
        return num
    elif ">" in s:
        num = s.replace(">", "")
        num = s.replace("%", "")
        num = float(num) / 100
        return num
    elif "<" in s:
        num = s.replace("<", "")
        num = float(num) / 100
        return num
    else:
        return 0.003

In [74]:
df_h3 = df_h3.assign(Playoffs_Prob = lambda x: x["MAKE PLAYOFFS"].apply(cleanPercent))

In [75]:
df_h3 = df_h3.assign(Division_Prob = lambda x: x["WIN DIVISION"].apply(cleanPercent))

In [76]:
df_h3 = df_h3.assign(Bye_Prob = lambda x: x["1st-Round Bye"].apply(cleanPercent))

In [77]:
df_h3 = df_h3.assign(SB_Prob = lambda x: x["Win Superbowl"].apply(cleanPercent))

In [78]:
df_h3.columns

Index(['ELO WITH QB', 'ELO CHANGE', 'CURRENT QB ADJ', 'DIVISION', 'PROJ WINS',
       'PROJ LOSES', 'POINT DIFF', 'MAKE PLAYOFFS', 'WIN DIVISION',
       '1st-Round Bye', 'Win Superbowl', 'Before Week', 'Year', 'REAL_WINS2',
       'REAL_LOSSES2', 'REAL_TIES', 'PROJ_WINS3', 'PROJ_LOSS3', 'FinalName',
       'Playoffs_Prob', 'Division_Prob', 'Bye_Prob', 'SB_Prob'],
      dtype='object')

In [79]:
">99".replace(">", "")

'99'

In [80]:
def cleanPoints(pts):
    pts = str(pts)
    if "+" in pts:
        pts = pts.replace("+", "")
        pts = float(pts)
        return pts
    elif "-" in pts:
        pts = pts.replace("-", "")
        pts = float(pts)
        return -pts
    else:
        return 0.00

In [81]:
df_h3 = df_h3.assign(Points_Diff = lambda x: x['POINT DIFF'].apply(cleanPoints))

In [82]:
df_h3.columns

Index(['ELO WITH QB', 'ELO CHANGE', 'CURRENT QB ADJ', 'DIVISION', 'PROJ WINS',
       'PROJ LOSES', 'POINT DIFF', 'MAKE PLAYOFFS', 'WIN DIVISION',
       '1st-Round Bye', 'Win Superbowl', 'Before Week', 'Year', 'REAL_WINS2',
       'REAL_LOSSES2', 'REAL_TIES', 'PROJ_WINS3', 'PROJ_LOSS3', 'FinalName',
       'Playoffs_Prob', 'Division_Prob', 'Bye_Prob', 'SB_Prob', 'Points_Diff'],
      dtype='object')

In [84]:
df_h3.tail()

,ELO WITH QB,ELO CHANGE,CURRENT QB ADJ,DIVISION,PROJ WINS,PROJ LOSES,POINT DIFF,MAKE PLAYOFFS,WIN DIVISION,1st-Round Bye,...,REAL_LOSSES2,REAL_TIES,PROJ_WINS3,PROJ_LOSS3,FinalName,Playoffs_Prob,Division_Prob,Bye_Prob,SB_Prob,Points_Diff
3615,1406,-24.0,NaN,NFC North,6-10,NaN,-78.4,5%,<1%,<1%,...,5,0,6,10,Detroit Lions,0.050,0.003,0.003,0.003,-78.4
3616,1367,14.0,NaN,NFC East,4-12,NaN,-94.1,7%,7%,<1%,...,7,0,4,12,New York Giants,0.070,0.070,0.003,0.003,-94.1
3617,1329,-3.0,-13.0,NFC East,4-12,NaN,-134.1,6%,6%,<1%,...,7,0,4,12,Dallas Cowboys,0.060,0.060,0.003,0.003,-134.1
3618,1298,-8.0,-91.0,AFC South,2-14,NaN,-180.8,<1%,<1%,<1%,...,7,0,2,14,Jacksonville Jaguars,0.003,0.003,0.003,0.003,-180.8
3619,1295,-17.0,1.0,AFC East,2-14,NaN,-217.7,<1%,—,—,...,9,0,2,14,New York Jets,0.003,0.003,0.003,0.003,-217.7

In [86]:
final_five_df = df_h3.loc[:, ["FinalName", "DIVISION", "ELO WITH QB", "ELO CHANGE", "CURRENT QB ADJ", "Points_Diff",
             'Playoffs_Prob', 'Division_Prob', 'Bye_Prob', 'SB_Prob','PROJ_WINS3', 'PROJ_LOSS3',
              'REAL_WINS2','REAL_LOSSES2', 'REAL_TIES',
              'Before Week', 'Year']]

In [87]:
final_five_df.to_csv("ELO_cleaned.csv", index=False)